var math=75.25;
var biology=65;
var chemistry=80;
var physics=35.45;
var bangla=99.50;
var totalSub=5;
sumOfMarks=math+biology+chemistry+physics+bangla;
avg=sumOfMarks/totalSub;
var Avg=avg.toFixed(2);
console.log(Avg);